
# el archivo ejecutable generado
OUT_LIB=libmessage.a

include ../.config.h
 
# archivos a compilar
OBJECTS=MessageHandler.o 

# paths
vpath %.m message

# include de reglas de compilacion 
include includes.mak

# includes
INCLUDES=$(ALL_INCLUDES)
		 

