/*
 *	lcd.h	
 */

#ifndef  __LCD_DRIVER_H__
#define  __LCD_DRIVER_H__ 

/* ioctl defs */
#define LCD_IOC_MAGIC 'x'
#define LCD_OK 0

#define LCD_IOCTSETTABSTOP	 	_IO(LCD_IOC_MAGIC, 1)
#define LCD_IOCTSETCURSORXY	 	_IO(LCD_IOC_MAGIC, 2)
#define LCD_IOCSPROGRAMCHAR	 	_IOW(LCD_IOC_MAGIC, 3, struct LCDProgramChar) 
#define LCD_IOCTSETTEXTBLINK 		_IO(LCD_IOC_MAGIC, 4)
#define LCD_IOCTSETCURSORBLINK 		_IO(LCD_IOC_MAGIC, 5)
#define LCD_IOCTSETCURSORSTATE 		_IO(LCD_IOC_MAGIC, 6)
#define LCD_IOCTSETDISPLAYSTATE		_IO(LCD_IOC_MAGIC, 7)
#define LCD_IOCTREOPEN		_IO(LCD_IOC_MAGIC, 8)
#define LCD_IOCTFONT			_IO(LCD_IOC_MAGIC, 9)
#define LCD_IOCQNUMLINES		_IO(LCD_IOC_MAGIC, 10)
#define LCD_IOCQNUMCHARS		_IO(LCD_IOC_MAGIC, 11)
#define LCD_IOCCLEARDISPLAY		_IO(LCD_IOC_MAGIC, 12)

#define LCD_IOC_MAXNR			13 



#endif

