del libmain.a
del libtelesup.a
del libmessage.a
del libui.a
del libsystem.a
del libtariff.a
del libvisor.a
del libaudit.a
del libworkstation.a
del libreports.a
del libdao.a
del libsettings.a
del libxml.a
del libbill.a
del libsysdb.a
del libsysio.a
del libsysnet.a
del libsysos.a
del libsysutil.a
del libsysdev.a
del libsysui.a
del libsysprinter.a
del libsms.a
