#ifndef USER_INTERFACE_EXCEPTS_H
#define USER_INTERFACE_EXCEPTS_H

#include "excepts.h"

#define USER_INTERFACE_EXCEPT									12000

#define UI_GENERAL_EX													(USER_INTERFACE_EXCEPT)
#define UI_COULD_NOT_OPEN_SCREEN_DRIVER_EX		(USER_INTERFACE_EXCEPT + 1)
#define UI_SCREEN_OUT_OF_RANGE_EX							(USER_INTERFACE_EXCEPT + 2)
#define UI_VALUE_TOO_BIG_EX										(USER_INTERFACE_EXCEPT + 4)
#define UI_NULL_VALUE_EX											(USER_INTERFACE_EXCEPT + 5)
#define UI_MIN_VALUE_EX												(USER_INTERFACE_EXCEPT + 6)
#define UI_MAX_VALUE_EX												(USER_INTERFACE_EXCEPT + 7)
#define UI_INDEX_OUT_OF_RANGE_EX							(USER_INTERFACE_EXCEPT + 8)
#define UI_BAD_ACTION_METHOD_EX								(USER_INTERFACE_EXCEPT + 9)
#define UI_CAN_NOT_FOCUS_COMPONENT_EX					(USER_INTERFACE_EXCEPT + 10)
#define UI_BAD_DIALOG_MODE_EX									(USER_INTERFACE_EXCEPT + 11)

#define UI_INVALID_DATE_EX										(USER_INTERFACE_EXCEPT + 12)
#define UI_INVALID_TIME_EX										(USER_INTERFACE_EXCEPT + 13)

#define UI_INVALID_DATE_TIME_EX               (USER_INTERFACE_EXCEPT + 14)
#define UI_INVALID_INFORMATION_EX             (USER_INTERFACE_EXCEPT + 15)
#define UI_PRODUCT_NOT_SELECTED_EX            (USER_INTERFACE_EXCEPT + 16)
#define UI_INCORRECT_PRODUCT_QTY_EX           (USER_INTERFACE_EXCEPT + 17)
#define UI_WRONG_DATE_EX                      (USER_INTERFACE_EXCEPT + 18)
#define UI_NULLED_EX                          (USER_INTERFACE_EXCEPT + 19)
#define UI_INVALID_RANGE                      (USER_INTERFACE_EXCEPT + 20)
#define UI_BIG_RANGE                      		(USER_INTERFACE_EXCEPT + 21)


 
#endif
