# el archivo ejecutable generado
OUT_LIB=libbill.a

include ../.config.h

# archivos a compilar
OBJECTS=Round.o
  
vpath %.m bill/
vpath %.m bill/round

include includes.mak

# includes
INCLUDES=$(ALL_INCLUDES)
		 

