
# el archivo ejecutable generado
OUT_LIB=libxml.a

include ../.config.h
 
# archivos a compilar
OBJECTS=XMLConstructor.o ReportXMLConstructor.o

# paths
vpath %.m xml

# include de reglas de compilacion 
include includes.mak

# includes
INCLUDES=$(ALL_INCLUDES)
		 

