#ifndef SETTINGS_EXCEPTS_H
#define SETTINGS_EXCEPTS_H

#include "system/lang/all.h"

#define SETTINGS_EXCEPT	105000

/* SYSTEM CONFIGURATION */
#define INVALID_PARAM_EX	                   							      (SETTINGS_EXCEPT + 1)
#define REFERENCE_NOT_FOUND_EX		                  			      (SETTINGS_EXCEPT + 2)
#define INVALID_REFERENCE_EX						                        (SETTINGS_EXCEPT + 3)
#define DAO_DUPLICATED_REFERENCE_EX			                        (SETTINGS_EXCEPT + 4)
#define DAO_NULLED_VALUE_EX							                        (SETTINGS_EXCEPT + 5)
#define DAO_OUT_OF_RANGE_VALUE_EX				                        (SETTINGS_EXCEPT + 6)
#define DAO_ENTITY_ALREADY_ACTIVATED_EX		                      (SETTINGS_EXCEPT + 7)
#define DAO_ENTITY_ALREADY_DEACTIVATED_EX	                      (SETTINGS_EXCEPT + 8) 
#define DAO_ENTITY_IN_USE									                      (SETTINGS_EXCEPT + 9) 
#define INEXISTENT_USER_EX								                      (SETTINGS_EXCEPT + 10)
#define NO_USER_LOGGED_IN_EX							                      (SETTINGS_EXCEPT + 11)
#define NO_CABIN_AVAILABLE_EX							                      (SETTINGS_EXCEPT + 12)
#define CANNOT_CHANGE_DATE_TIME_WITH_CABIN_ENABLED_EX           (SETTINGS_EXCEPT + 13)
#define CANNOT_REMOVE_CURRENT_USER_EX                           (SETTINGS_EXCEPT + 14)
#define CANNOT_REMOVE_USER_EX                                   (SETTINGS_EXCEPT + 15)
#define CABIN_IS_ENABLE_EX                                      (SETTINGS_EXCEPT + 16)
#define TAXES_QTY_INCORRECT_EX                                  (SETTINGS_EXCEPT + 17)
#define CANNOT_SET_FORBIDDEN_CALL_TYPES_WITH_CABIN_ENABLED_EX   (SETTINGS_EXCEPT + 18)
#define CANNOT_REMOVE_SUPPORT_USER_EX                           (SETTINGS_EXCEPT + 19)
#define CANNOT_ADD_SUPPORT_USER_EX                              (SETTINGS_EXCEPT + 20)
#define CANNOT_MODIFY_SUPPORT_USER_EX                           (SETTINGS_EXCEPT + 21)
#define CANNOT_REMOVE_TAX_WITH_ASSOCIATIONS_EX                  (SETTINGS_EXCEPT + 22)
#define CANNOT_REMOVE_DEFAULT_TELESUP_EX												(SETTINGS_EXCEPT + 23)
#define REFERENTIAL_INTEGRITY_EX																(SETTINGS_EXCEPT + 24)
#define ONLY_ONE_TELESUP_ALLOWED_EX															(SETTINGS_EXCEPT + 25)
#define NO_PC_AVAILABLE_EX							                        (SETTINGS_EXCEPT + 26)
#define SYSTEM_BLOCKED_EX 																			(SETTINGS_EXCEPT + 27)
#define HAS_REACHED_THRESHOLD_EX																(SETTINGS_EXCEPT + 28)
#define CANNOT_REMOVE_LINE_WITH_ASSOCIATIONS_EX									(SETTINGS_EXCEPT + 29)
#define DUPLICATED_TAX_NAME_EX			                            (SETTINGS_EXCEPT + 30)
#define NULLED_NAME_EX        			                            (SETTINGS_EXCEPT + 31)
#define NULLED_IDENTIFIER_EX        			                      (SETTINGS_EXCEPT + 32)
#define DUPLICATED_IDENTIFIER_EX        			                  (SETTINGS_EXCEPT + 33)
#define CANNOT_REMOVE_USER_ADMIN      			                    (SETTINGS_EXCEPT + 34)
#define USER_ASSOCIATED_PROFILE_EX														  (SETTINGS_EXCEPT + 35)
#define USER_ASSOCIATED_CHILD_PROFILE_EX											  (SETTINGS_EXCEPT + 36)
#define NOT_DELETE_PROFILE_ADMIN_EX											        (SETTINGS_EXCEPT + 37)
#define NULL_PROFILE_NAME_EX											              (SETTINGS_EXCEPT + 38)
#define DAO_DUPLICATED_DUAL_ACCESS_EX											      (SETTINGS_EXCEPT + 39)
#define DAO_EQUALS_DUAL_ACCESS_EX											          (SETTINGS_EXCEPT + 40)
#define INACTIVE_USER_EX																				(SETTINGS_EXCEPT + 41)
#define DAO_DUPLICATED_PROFILE_NAME_EX													(SETTINGS_EXCEPT + 42)
#define SIGN_AUTHORIZATION_ERROR_EX															(SETTINGS_EXCEPT + 43)
#define SIGN_GENERATION_ERROR_EX																(SETTINGS_EXCEPT + 44)
#define KEY_FILES_NOT_FOUND_EX																	(SETTINGS_EXCEPT + 45)
#define USER_HAS_NOT_GOT_DOOR_ACCESS_EX													(SETTINGS_EXCEPT + 46)
#define MODULE_NOT_FOUND_EX																			(SETTINGS_EXCEPT + 47)
#define MODULE_CANNOT_BE_EXECUTED_EX														(SETTINGS_EXCEPT + 48)

#define WRONG_USER_PASSWORD_EX																	(SETTINGS_EXCEPT + 57)
#define WRONG_USER_LOGIN_NAME_EX																(SETTINGS_EXCEPT + 58)
#define DALLAS_KEY_REQUIRED_EX																	(SETTINGS_EXCEPT + 59)
#define INVALID_DALLAS_KEY_EX																		(SETTINGS_EXCEPT + 60)
#define LOGIN_NAME_AND_PIN_REQUIRED_EX													(SETTINGS_EXCEPT + 61)
#define MAX_SECONDARY_HARDWARE_ACCESS_USERS_EX									(SETTINGS_EXCEPT + 62)
#define PIN_REQUIRED_EX																					(SETTINGS_EXCEPT + 63)
#define DURESS_PIN_REQUIRED_EX																	(SETTINGS_EXCEPT + 64)
#define WRONG_USER_NAME_OR_PASSWORD_EX													(SETTINGS_EXCEPT + 65)
#define SWIPE_CARD_KEY_REQUIRED_EX															(SETTINGS_EXCEPT + 66)
#define INVALID_SWIPE_CARD_KEY_EX																(SETTINGS_EXCEPT + 67)
#define DALLAS_NOT_AVAILABLE_EX																	(SETTINGS_EXCEPT + 68)
#define SWIPE_CARD_NOT_AVAILABLE_EX															(SETTINGS_EXCEPT + 69)
#define DALLAS_OR_SWIPE_CARD_KEY_REQUIRED_EX										(SETTINGS_EXCEPT + 70)
#define USER_NOT_EXIST_EX																				(SETTINGS_EXCEPT + 71)
#define DEVICE_KEY_REQUIRED_EX																	(SETTINGS_EXCEPT + 72)
#define USER_DYNAM_PIN_CANNOT_CHANGE_PASS_EX										(SETTINGS_EXCEPT + 73)
#define CANNOT_LOGIN_IN_TELESUP_EX																(SETTINGS_EXCEPT + 74)
#define MAX_QTY_LOGIN_FAIL																(SETTINGS_EXCEPT + 75)


#endif 


