#ifndef UTIL_EXCEPTS_H
#define UTIL_EXCEPTS_H

#define UTIL_EXCEPT	6000

#define QUEUE_EX									    (UTIL_EXCEPT)
#define QUEUE_IS_FULL_EX					    (UTIL_EXCEPT + 1)
#define QUEUE_IS_EMPTY_EX					    (UTIL_EXCEPT + 2)

#define DATETIME_EX								    (UTIL_EXCEPT + 50)
#define NO_MORE_TOKENS_EX   			    (UTIL_EXCEPT + 51)
#define INVALID_CURRENT_TIME_EX		    (UTIL_EXCEPT + 52)
#define INVALID_NUMBER_TO_FORMAT_EX		(UTIL_EXCEPT + 52)

#define CONFIGURATION_NOT_FOUND_EX	(UTIL_EXCEPTS_H + 60)
#define INVALID_CONFIGURATION_FILE_EX	(UTIL_EXCEPTS_H + 61)

#define COL_OUT_OF_BOUNDS_EX			(UTIL_EXCEPT + 100)

#define INVALID_PATH_EX						(UTIL_EXCEPT + 200)


#endif
