#!/bin/sh

rm /rw/CT8016/data/audits*dat
rm /rw/CT8016/data/change_log*dat
rm /rw/CT8016/data/deposit*dat
rm /rw/CT8016/data/extraction*dat
rm /rw/CT8016/data/temp_deposit*dat
rm /rw/CT8016/data/zclose*dat
cp /rw/CT8016/initFiles/accepted_dep_value_bck.dat /rw/CT8016/data/accepted_dep_value.dat
cp /rw/CT8016/initFiles/acceptor_by_box_bck.dat /rw/CT8016/data/acceptor_by_box.dat
cp /rw/CT8016/initFiles/acceptor_by_cash_bck.dat /rw/CT8016/data/acceptor_by_cash.dat
cp /rw/CT8016/initFiles/acceptors_bck.dat /rw/CT8016/data/acceptors.dat
cp /rw/CT8016/initFiles/amount_settings_bck.dat /rw/CT8016/data/amount_settings.dat
cp /rw/CT8016/initFiles/bill_settings_bck.dat /rw/CT8016/data/bill_settings.dat
cp /rw/CT8016/initFiles/box_bck.dat /rw/CT8016/data/box.dat
cp /rw/CT8016/initFiles/cash_reference_bck.dat /rw/CT8016/data/cash_reference.dat
cp /rw/CT8016/initFiles/cim_cash_bck.dat /rw/CT8016/data/cim_cash.dat
cp /rw/CT8016/initFiles/cim_settings_bck.dat /rw/CT8016/data/cim_settings.dat
cp /rw/CT8016/initFiles/commercial_state_bck.dat /rw/CT8016/data/commercial_state.dat
cp /rw/CT8016/initFiles/connections_bck.dat /rw/CT8016/data/connections.dat
cp /rw/CT8016/initFiles/currency_dep_value_bck.dat /rw/CT8016/data/currency_dep_value.dat
cp /rw/CT8016/initFiles/denominations_bck.dat /rw/CT8016/data/denominations.dat
cp /rw/CT8016/initFiles/door_by_box_bck.dat /rw/CT8016/data/door_by_box.dat
cp /rw/CT8016/initFiles/doors_bck.dat /rw/CT8016/data/doors.dat
cp /rw/CT8016/initFiles/doors_by_user_bck.dat /rw/CT8016/data/doors_by_user.dat
cp /rw/CT8016/initFiles/dual_access_bck.dat /rw/CT8016/data/dual_access.dat
cp /rw/CT8016/initFiles/licence_modules_bck.dat /rw/CT8016/data/licence_modules.dat
cp /rw/CT8016/initFiles/printing_settings_bck.dat /rw/CT8016/data/printing_settings.dat
cp /rw/CT8016/initFiles/profiles_bck.dat /rw/CT8016/data/profiles.dat
cp /rw/CT8016/initFiles/regional_settings_bck.dat /rw/CT8016/data/regional_settings.dat
cp /rw/CT8016/initFiles/telesups_bck.dat /rw/CT8016/data/telesups.dat
cp /rw/CT8016/initFiles/users_bck.dat /rw/CT8016/data/users.dat