
# el archivo ejecutable generado
OUT_LIB=libaudit.a
 
# archivos a compilar
OBJECTS=Audit.o Event.o EventCategory.o

include ../.config.h

# paths
vpath %.m audit

# include de reglas de compilacion 
include includes.mak

# includes
INCLUDES=$(ALL_INCLUDES)
		 

