#ifndef DB_EXCEPTS_H
#define DB_EXCEPTS_H

#include "excepts.h"

#define DB_EXCEPT						7000

#define DATABASE_NOT_RUNNING_EX		(DB_EXCEPT + 1)
#define	NO_CURRENT_RECORD_EX			(DB_EXCEPT + 2)
#define	FIELD_NOT_FOUND_EX				(DB_EXCEPT + 3)
#define END_OF_RECORDSET_EX				(DB_EXCEPT + 4)
#define BEGIN_OF_RECORDSET_EX			(DB_EXCEPT + 5)
#define READ_ONLY_FIELD_EX				(DB_EXCEPT + 6)
#define TABLE_NOT_FOUND_EX				(DB_EXCEPT + 7)
#define TABLE_NOT_OPEN_EX					(DB_EXCEPT + 8)
#define CANNOT_DELETE_RECORD_EX   (DB_EXCEPT + 9)
#define INVALID_FIELD_SIZE_EX			(DB_EXCEPT + 10)

#define TRANSACTION_NOT_STARTED_EX (DB_EXCEPT + 20)
#define CANNOT_REMOVE_TRANSACTION_LOG_EX (DB_EXCEPT + 21)
#define INVALID_SEEK_EX					(DB_EXCEPT + 22)
#define INVALID_DB_OPERATION_EX			(DB_EXCEPT + 23)
#define NO_PRIMARY_KEY_EX				(DB_EXCEPT + 24)

// Exceptiones SQL
#define	GENERAL_SQL_EX					      (DB_EXCEPT + 100)
#define SQL_CONNECTION_EX				      (DB_EXCEPT + 101)
#define SQL_QUERY_EX					        (DB_EXCEPT + 102)
#define SQL_INVALID_PRIMARY_KEY_EX		(DB_EXCEPT + 103)
#define SQL_INVALID_META_DATA_EX      (DB_EXCEPT + 104)
#define SQL_INVALID_GENERATOR_EX      (DB_EXCEPT + 105)

#endif
