#!/bin/bash

export CT_HOME=../.. 
case $1 in

	arm-linux)
		source /opt/fsl-imx-x11/4.1.15-1.2.0/environment-setup-cortexa9hf-vfp-neon-poky-linux-gnueabi
		export PLATFORM=arm-linux
		echo "Arm-linux Enviroment"
	;;
	linux)
		export AR=ar
		export CC=gcc
		export PLATFORM=linux
		echo "Linux Enviroment"
	;;

esac
