#!/bin/bash

export CT_HOME=../.. 
case $1 in

	arm-linux)
		source /opt/fslc-framebuffer/2.2.1/environment-setup-armv7at2hf-neon-fslc-linux-gnueabi
		export PLATFORM=arm-linux
		export OBJC_BASE=/home/razor/Work/poc/objc-3.3.2
		echo "Arm-linux Enviroment"
	;;
	linux)
		export AR=ar
		export CC=gcc
		export PLATFORM=linux
		echo "Linux Enviroment"
	;;

esac
